# Generated by Django 2.2.3 on 2019-07-26 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionarios',
            name='imagem',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
