# Generated by Django 2.2.3 on 2019-07-21 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_hora_extra', '0002_horaextra_horas'),
    ]

    operations = [
        migrations.AddField(
            model_name='horaextra',
            name='utilizada',
            field=models.BooleanField(default=False),
        ),
    ]
