# Generated by Django 2.2.2 on 2019-06-22 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0002_documento_pertence'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='documento',
            field=models.FileField(default='', upload_to='documentos'),
            preserve_default=False,
        ),
    ]
